### ISSUE TITLE
Module status

### ISSUE THREAD

**Issue by bow** [brentp/align#1]
Hi @brentp,

This may sound quite late (I know the package was worked on about 6 years go), but I'm wondering if you are still planning on making updates / changes to this package.

The reason I'm asking is because I couldn't find a nice, pythonic package that does simple semiglobal alignment and is compatible with Python 3. This package comes close, in my opinion (thanks for writing it by the way ~ much appreciated!), but I could see there are still room for its improvement.

I did apply [some changes](https://github.com/bow/align/commits/master) to a fork of this package so that it works nicer under Python 3 (particularly the imports), but I can imagine lots more can be done. Off the top of my head:
- Returning not only a single best alignment but all of the alignments with the same max score (I've tried doing this only for the semiglobal method, but ideally it should be available to all methods. My changes are also quite badly written for now).
- Returning also the alignment positions of each sequences
- Making the alignment case-insensitive and adding more scoring matrices (e.g. PAM100)
- All the above updates on the Cython version
- Updating the tests
- Updating the installation (now it requires numpy to be present first since there is `import numpy` in `setup.py` without any try-except block)

So I'm wondering, are there any plans on such updates for the future? An analysis I'm doing now requires some simple alignments (preferrably with a nice Python interface). It would be nice if somehow there are plans to do that already :) ~ but if not, I can also try working on it.

**Comment by brentp** [comment]
I don't have any plans to make those updates, but I'm happy to accept PR's to do so. Especially if they are well tested. I had a quick look at your changes and they seem reasonable.

**Comment by bow** [comment]
That sounds ok :). I'll try to make some changes then.

I do have one more question about the `aligner` function:  what's the reason behind using `flip` when returning? I was thinking of removing it so that the returned tuple's items are more predictable (e.g. first item is always sequence 1), but I'm not sure if this is ok.

**Comment by brentp** [comment]
I'm fine with removing `flip`

**Comment by bow** [comment]
Great then :). I've made more (almost) backwards compatible changes (pep8, project setup, tests refactor) and also added tox + travis (on Python 2.7 and 3.5 ~ both running the tests just fine). I'm now working on some of the updates I mentioned above (i.e. the backwards-incompatible changes).

One more question: I saw the license is MIT in the README and BSD in setup.py. Which one is actually correct?

Also, feel free to stop me / let me know if you feel some of these changes are not acceptable.

**Comment by brentp** [comment]
let's go BSD. I think that was the original.

**Comment by bow** [comment]
Ok, I've removed all mentions of the license being MIT now.

I've also added a [HISTORY.rst file](https://github.com/bow/align/blob/63c95990e8101fe338dff619a783990c0934e1aa/HISTORY.rst) outlining the changes that have been made.

I think the biggest change is the return type of the `aligner` function now (and the number of items returned). All the tests have been updated to reflect this (and I've added several of my own).

There is still one limitation of the current global method when `max_hits` is set to non-1 values now. I still only return one optimal alignment in that case, since returning all optimal global alignments would mean changing the backtrack procedure even more. Perhaps this is something for later. Also, I didn't end up removing `flip`.

Would you mind taking a look to see if the changes are ok? If so, I can then start updating the Cython part (I haven't touched it yet).

**Comment by brentp** [comment]
can you put it in a pull request? are there any changes on the speed?

**Comment by bow** [comment]
Sure ~ you should be able to see it now. I haven't made any performance tweaks, and I can only expect the speed to be slightly slower (if there are any changes in speed at all). I'll post some quick benchmarks in the PR page.
